server:
  port: 8080
spring:
  application:
    name: bbs
  profiles:
    active: dev

logging:
  level:
    info.asshead: debug
  file: logs/bbs.log

---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456aB!
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 10
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 6000
    jpa:
      show-sql: false

---
spring:
  profiles: test
  jpa:
    show-sql: true
  datasource:
    schema: classpath:init_table.sql
    driverClassName: org.h2.Driver

---
spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: $DB_URL
    username: $DB_USER
    password: $DB_PASS
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: $MAX_ACTIVE
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 6000